In [1]:
import pandas as pd

#load the Dataset
df=pd.read_csv("Titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
#check Dataset information
print("Dataset shape :",df.shape)
df.info()
print("\nMissing values before cleaning :\n")
print(df.isnull().sum())

Dataset shape : (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Missing values before cleaning :

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
#Handle missing values

df["Age"]=df["Age"].fillna(df["Age"].median())
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])

#Drop cabin column due to excessive missing values
df["Cabin"].isnull().sum()
df.drop(columns=["Cabin"],inplace=True)

#verify missing values after cleaning
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [4]:
#Remove duplicates

df.drop_duplicates(inplace=True)
print("Dataset shape after removing duplicates :",df.shape)

Dataset shape after removing duplicates : (891, 11)

In [6]:
#Convert data types

df["Pclass"]=df["Pclass"].astype("category")
df["Sex"]=df["Sex"].astype("category")
df["Embarked"]=df["Embarked"].astype("category")

print(df.dtypes)

PassengerId       int64
Survived          int64
Pclass         category
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
dtype: object

In [7]:
#rename columns for better readability 
df.rename(columns={
    "PassengerId":"Passenger_ID",
    "Pclass":"Passenger_Class",
    "Name":"Passenger_Name",
    "Sex":"Gender",
    "SibSp":"Siblings_Spouses",
    "Parch":"Parents_Children",
    "Fare":"Ticket_Fare"
},inplace=True)

df.head()

,Passenger_ID,Survived,Passenger_Class,Passenger_Name,Gender,Age,Siblings_Spouses,Parents_Children,Ticket,Ticket_Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [8]:
#Save the cleaned dataset
df.to_csv("Titanic_Cleaned.csv",index=False)
print("Cleaned and preprocessed dataset saved as 'Titanic_cleaned.csv'.")

Cleaned and preprocessed dataset saved as 'Titanic_cleaned.csv'.